version: "3.7"

services:
  proxy:
    container_name: wt-proxy
    image: nginx:mainline-alpine3.18-slim
    ports:
      - 3500:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal
    depends_on:
      - php
      - mariadb

  php:
    container_name: wt-php
    build: './docker/php'
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - internal
    depends_on:
      - mariadb

  phpmyadmin:
    container_name: wt-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    networks:
      - internal
    depends_on:
      - mariadb

  mariadb:
    container_name: wt-mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - wt-mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: DevelopmentPassword
    networks:
      - internal

volumes:
  wt-mariadb-data:


networks:
  internal:
    driver: bridge
