CREATE OR REPLACE DATABASE workout_tracker;
USE workout_tracker;

-- Group
CREATE OR REPLACE TABLE `Group` (
	id BINARY(16) NOT NULL DEFAULT UUID() PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	description VARCHAR(256) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

-- Permission
CREATE OR REPLACE TABLE `Permission` (
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	description VARCHAR(256) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

-- Type
CREATE OR REPLACE TABLE `Type` (
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	description VARCHAR(256) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

-- User
CREATE OR REPLACE TABLE `User` (
	id BINARY(16) NOT NULL DEFAULT UUID() PRIMARY KEY,
	username VARCHAR(64) NOT NULL,
	first_name VARCHAR(64) NOT NULL,
	last_name VARCHAR(64) NOT NULL,
	email VARCHAR(254) NOT NULL,
	group_id BINARY(16),
	permission TINYINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_permission` FOREIGN KEY (permission) REFERENCES `Permission` (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT `fk_group_id` FOREIGN KEY (group_id) REFERENCES `Group` (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	INDEX ix_permission (permission),
	INDEX ix_group_id (group_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

-- Workout
CREATE OR REPLACE TABLE `Workout` (
	id BINARY(16) NOT NULL DEFAULT UUID() PRIMARY KEY,
	owner BINARY(16) NOT NULL,
	type TINYINT UNSIGNED NOT NULL,
	start_time DATETIME NULL,
	end_time DATETIME NULL,
	CONSTRAINT `fk_owner` FOREIGN KEY (owner) REFERENCES User (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT `fk_type` FOREIGN KEY (type) REFERENCES Type (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	INDEX ix_owner (owner),
	INDEX ix_type (type),
	INDEX ix_start_time (start_time),
	INDEX ix_end_time (end_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;